import datetime
import decimal

from sqlalchemy import (
    BINARY,
    DateTime,
    Identity,
    Index,
    Integer,
    Numeric,
    PrimaryKeyConstraint,
    SmallInteger,
    Unicode,
    text,
)
from sqlalchemy.dialects.mssql import TINYINT
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class Address(Base):
    __tablename__ = 'BPADDRESS'
    __table_args__ = (
        PrimaryKeyConstraint('ROWID', name='BPADDRESS_ROWID'),
        Index('BPADDRESS_BPA0', 'BPATYP_0', 'BPANUM_0', 'BPAADD_0', unique=True),
        Index('BPADDRESS_SPE_BPA0', 'BPANUM_0', 'BPAADD_0'),
        {'schema': 'MINP'},
    )

    BPATYP_0: Mapped[int] = mapped_column(TINYINT)
    BPANUM_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    BPAADD_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    BPADES_0: Mapped[str] = mapped_column(Unicode(30, 'Latin1_General_BIN2'))
    BPABID_0: Mapped[str] = mapped_column(Unicode(30, 'Latin1_General_BIN2'))
    BPAADDFLG_0: Mapped[int] = mapped_column(TINYINT)
    BPAADDLIG_0: Mapped[str] = mapped_column(Unicode(50, 'Latin1_General_BIN2'))
    BPAADDLIG_1: Mapped[str] = mapped_column(Unicode(50, 'Latin1_General_BIN2'))
    BPAADDLIG_2: Mapped[str] = mapped_column(Unicode(50, 'Latin1_General_BIN2'))
    POSCOD_0: Mapped[str] = mapped_column(Unicode(10, 'Latin1_General_BIN2'))
    CTY_0: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    CODSEE_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    SAT_0: Mapped[str] = mapped_column(Unicode(35, 'Latin1_General_BIN2'))
    CRY_0: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    CRYNAM_0: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    TEL_0: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    TEL_1: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    TEL_2: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    TEL_3: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    TEL_4: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    FAX_0: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    MOB_0: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    WEB_0: Mapped[str] = mapped_column(Unicode(80, 'Latin1_General_BIN2'))
    WEB_1: Mapped[str] = mapped_column(Unicode(80, 'Latin1_General_BIN2'))
    WEB_2: Mapped[str] = mapped_column(Unicode(80, 'Latin1_General_BIN2'))
    WEB_3: Mapped[str] = mapped_column(Unicode(80, 'Latin1_General_BIN2'))
    WEB_4: Mapped[str] = mapped_column(Unicode(80, 'Latin1_General_BIN2'))
    FCYWEB_0: Mapped[str] = mapped_column(Unicode(250, 'Latin1_General_BIN2'))
    EXTNUM_0: Mapped[str] = mapped_column(Unicode(30, 'Latin1_General_BIN2'))
    EXPNUM_0: Mapped[int] = mapped_column(Integer)
    ADRVAL_0: Mapped[int] = mapped_column(TINYINT)
    GLNCOD_0: Mapped[str] = mapped_column(Unicode(13, 'Latin1_General_BIN2'))
    CRN_0: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    CREDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    UPDDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    CREUSR_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    UPDUSR_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    CREDATTIM_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    UPDDATTIM_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    AUUID_0: Mapped[bytes] = mapped_column(BINARY(16))
    UPDTICK_0: Mapped[int] = mapped_column(Integer, server_default=text('((1))'))
    ROWID: Mapped[decimal.Decimal] = mapped_column(
        Numeric(38, 0),
        Identity(start=decimal.Decimal('1'), increment=decimal.Decimal('1')),
        primary_key=True,
    )


class BPARTNER(Base):
    __tablename__ = 'BPARTNER'
    __table_args__ = (
        PrimaryKeyConstraint('ROWID', name='BPARTNER_ROWID'),
        Index('BPARTNER_BPR0', 'BPRNUM_0', unique=True),
        Index('BPARTNER_BPR1', 'BPRSHO_0'),
        Index('BPARTNER_BPR2', 'BETFCY_0', 'FCY_0', 'BPRNUM_0', unique=True),
        {'schema': 'MINP'},
    )

    UPDTICK_0: Mapped[int] = mapped_column(Integer, server_default=text('((1))'))
    BPRNUM_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    ENAFLG_0: Mapped[int] = mapped_column(TINYINT)
    BRGCOD_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    BRGOBJ_0: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    BPRNAM_0: Mapped[str] = mapped_column(Unicode(35, 'Latin1_General_BIN2'))
    BPRNAM_1: Mapped[str] = mapped_column(Unicode(35, 'Latin1_General_BIN2'))
    BPRSHO_0: Mapped[str] = mapped_column(Unicode(10, 'Latin1_General_BIN2'))
    EECNUM_0: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    BETFCY_0: Mapped[int] = mapped_column(TINYINT)
    FCY_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    CRY_0: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    CRN_0: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    NAF_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    CUR_0: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    LAN_0: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    BPRLOG_0: Mapped[str] = mapped_column(Unicode(10, 'Latin1_General_BIN2'))
    VATNUM_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    FISCOD_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    GRUGPY_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    GRUCOD_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    BPCFLG_0: Mapped[int] = mapped_column(TINYINT)
    BPSFLG_0: Mapped[int] = mapped_column(TINYINT)
    CCNFLG_0: Mapped[int] = mapped_column(SmallInteger)
    BPTFLG_0: Mapped[int] = mapped_column(TINYINT)
    FCTFLG_0: Mapped[int] = mapped_column(TINYINT)
    REPFLG_0: Mapped[int] = mapped_column(TINYINT)
    BPRACC_0: Mapped[int] = mapped_column(TINYINT)
    PPTFLG_0: Mapped[int] = mapped_column(TINYINT)
    PRVFLG_0: Mapped[int] = mapped_column(TINYINT)
    DOOFLG_0: Mapped[int] = mapped_column(TINYINT)
    ACCCOD_0: Mapped[str] = mapped_column(Unicode(10, 'Latin1_General_BIN2'))
    PTHFLG_0: Mapped[int] = mapped_column(SmallInteger)
    BPRFLG_0: Mapped[int] = mapped_column(TINYINT)
    BPRFLG_1: Mapped[int] = mapped_column(TINYINT)
    BPRFLG_2: Mapped[int] = mapped_column(TINYINT)
    BPRFLG_3: Mapped[int] = mapped_column(TINYINT)
    BPAADD_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    CNTNAM_0: Mapped[str] = mapped_column(Unicode(35, 'Latin1_General_BIN2'))
    BIDNUM_0: Mapped[str] = mapped_column(Unicode(30, 'Latin1_General_BIN2'))
    BIDCRY_0: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    ACS_0: Mapped[str] = mapped_column(Unicode(10, 'Latin1_General_BIN2'))
    EXPNUM_0: Mapped[int] = mapped_column(Integer)
    BPRGTETYP_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    BPRFBDMAG_0: Mapped[int] = mapped_column(TINYINT)
    MODPAM_0: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    ACCNONREI_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    LEGETT_0: Mapped[int] = mapped_column(TINYINT)
    CFOEXD_0: Mapped[int] = mapped_column(TINYINT)
    CREUSR_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    CREDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    UPDUSR_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    UPDDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    DOCTYP_0: Mapped[int] = mapped_column(SmallInteger)
    BPPFLG_0: Mapped[int] = mapped_column(TINYINT)
    CREDATTIM_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    UPDDATTIM_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    AUUID_0: Mapped[bytes] = mapped_column(BINARY(16))
    CPYREL_0: Mapped[int] = mapped_column(TINYINT)
    CSLBPR_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    REGNUM_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    VATNO_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    ZPAGITM_0: Mapped[int] = mapped_column(TINYINT)
    EORINUM_0: Mapped[str] = mapped_column(Unicode(35, 'Latin1_General_BIN2'))
    INTSRVCOD_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    ZEDITOR_0: Mapped[int] = mapped_column(TINYINT)
    RTGCOD_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    EINVTYP_0: Mapped[int] = mapped_column(SmallInteger)
    ZINTVSP_0: Mapped[int] = mapped_column(TINYINT)
    MAPCOD_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    ZAGENTE_0: Mapped[int] = mapped_column(TINYINT)
    ZGESFLG_0: Mapped[int] = mapped_column(TINYINT)
    ZANAFLG_0: Mapped[int] = mapped_column(TINYINT)
    ZEXPFLG_0: Mapped[int] = mapped_column(TINYINT)
    ROWID: Mapped[decimal.Decimal] = mapped_column(
        Numeric(38, 0),
        Identity(start=decimal.Decimal('1'), increment=decimal.Decimal('1')),
        primary_key=True,
    )


class BPCUSTOMER(Base):
    __tablename__ = 'BPCUSTOMER'
    __table_args__ = (
        PrimaryKeyConstraint('ROWID', name='BPCUSTOMER_ROWID'),
        Index('BPCUSTOMER_BPC0', 'BPCNUM_0', unique=True),
        Index('BPCUSTOMER_BPC1', 'BPCNAM_0'),
        Index('BPCUSTOMER_ZBPC0', 'ZCRYNAM_0', 'BPCNAM_0', 'BPCNUM_0', unique=True),
        {'schema': 'MINP'},
    )

    UPDTICK_0: Mapped[int] = mapped_column(Integer, server_default=text('((1))'))
    BPCNUM_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    BPCNAM_0: Mapped[str] = mapped_column(Unicode(35, 'Latin1_General_BIN2'))
    BPCSHO_0: Mapped[str] = mapped_column(Unicode(10, 'Latin1_General_BIN2'))
    BCGCOD_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    GRP_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    BPCTYP_0: Mapped[int] = mapped_column(TINYINT)
    BPCINV_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    BPAINV_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    BPCPYR_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    BPAPYR_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    BPCGRU_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    BPCRSK_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    BPAADD_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    BPDADD_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    CNTNAM_0: Mapped[str] = mapped_column(Unicode(35, 'Latin1_General_BIN2'))
    BPCSTA_0: Mapped[int] = mapped_column(TINYINT)
    PPTFLG_0: Mapped[int] = mapped_column(TINYINT)
    BPCBPSNUM_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    FCTNUM_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CUR_0: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    CHGTYP_0: Mapped[int] = mapped_column(TINYINT)
    COMCAT_0: Mapped[int] = mapped_column(TINYINT)
    REP_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    REP_1: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    VACBPR_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    VATEXN_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    PTE_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    FREINV_0: Mapped[int] = mapped_column(TINYINT)
    DEP_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    INVDTAAMT_0: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_1: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_2: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_3: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_4: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_5: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_6: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_7: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_8: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_9: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_10: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_11: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_12: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_13: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_14: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_15: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_16: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_17: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_18: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_19: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_20: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_21: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_22: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_23: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_24: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_25: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_26: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_27: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_28: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTAAMT_29: Mapped[decimal.Decimal] = mapped_column(Numeric(20, 5))
    INVDTA_0: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_1: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_2: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_3: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_4: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_5: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_6: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_7: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_8: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_9: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_10: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_11: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_12: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_13: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_14: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_15: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_16: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_17: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_18: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_19: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_20: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_21: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_22: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_23: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_24: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_25: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_26: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_27: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_28: Mapped[int] = mapped_column(SmallInteger)
    INVDTA_29: Mapped[int] = mapped_column(SmallInteger)
    TSCCOD_0: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    TSCCOD_1: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    TSCCOD_2: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    TSCCOD_3: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    TSCCOD_4: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    PRITYP_0: Mapped[int] = mapped_column(TINYINT)
    BPCREM_0: Mapped[str] = mapped_column(Unicode(250, 'Latin1_General_BIN2'))
    OSTCTL_0: Mapped[int] = mapped_column(TINYINT)
    OSTAUZ_0: Mapped[decimal.Decimal] = mapped_column(Numeric(27, 13))
    ORDMINAMT_0: Mapped[decimal.Decimal] = mapped_column(Numeric(27, 13))
    CDTISR_0: Mapped[decimal.Decimal] = mapped_column(Numeric(27, 13))
    CDTISRDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    BPCCDTISR_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    FUPTYP_0: Mapped[int] = mapped_column(TINYINT)
    FUPMINAMT_0: Mapped[decimal.Decimal] = mapped_column(Numeric(27, 13))
    SOIPER_0: Mapped[int] = mapped_column(TINYINT)
    PAYBAN_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    ACCCOD_0: Mapped[str] = mapped_column(Unicode(10, 'Latin1_General_BIN2'))
    DIE_0: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_1: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_2: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_3: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_4: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_5: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_6: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_7: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_8: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_9: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_10: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_11: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_12: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_13: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_14: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_15: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_16: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_17: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_18: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    DIE_19: Mapped[str] = mapped_column(Unicode(3, 'Latin1_General_BIN2'))
    CCE_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_1: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_2: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_3: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_4: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_5: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_6: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_7: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_8: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_9: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_10: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_11: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_12: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_13: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_14: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_15: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_16: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_17: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_18: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    CCE_19: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    MTCFLG_0: Mapped[int] = mapped_column(TINYINT)
    ORDTEX_0: Mapped[str] = mapped_column(Unicode(17, 'Latin1_General_BIN2'))
    INVTEX_0: Mapped[str] = mapped_column(Unicode(17, 'Latin1_General_BIN2'))
    LNDAUZ_0: Mapped[int] = mapped_column(TINYINT)
    OCNFLG_0: Mapped[int] = mapped_column(TINYINT)
    INVPER_0: Mapped[int] = mapped_column(TINYINT)
    DUDCLC_0: Mapped[int] = mapped_column(TINYINT)
    ORDCLE_0: Mapped[int] = mapped_column(TINYINT)
    ODL_0: Mapped[int] = mapped_column(TINYINT)
    DME_0: Mapped[int] = mapped_column(TINYINT)
    IME_0: Mapped[int] = mapped_column(TINYINT)
    BUS_0: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    ORIPPT_0: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    PITCDT_0: Mapped[int] = mapped_column(Integer)
    PITCPT_0: Mapped[int] = mapped_column(Integer)
    TOTPIT_0: Mapped[int] = mapped_column(Integer)
    COTCHX_0: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    COTPITRQD_0: Mapped[int] = mapped_column(Integer)
    CNTFIRDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    ORDFIRDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    QUOLASDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    CNTLASDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    CNTNEXDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    CNTLASTYP_0: Mapped[int] = mapped_column(TINYINT)
    CNTNEXTYP_0: Mapped[int] = mapped_column(TINYINT)
    ABCCLS_0: Mapped[int] = mapped_column(TINYINT)
    AGTPCP_0: Mapped[int] = mapped_column(SmallInteger)
    AGTSATTAX_0: Mapped[int] = mapped_column(SmallInteger)
    SATTAX_0: Mapped[str] = mapped_column(Unicode(1, 'Latin1_General_BIN2'))
    FLGSATTAX_0: Mapped[int] = mapped_column(SmallInteger)
    TPMCOD_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    DIA_0: Mapped[str] = mapped_column(Unicode(10, 'Latin1_General_BIN2'))
    BPCSNCDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    EXPNUM_0: Mapped[int] = mapped_column(Integer)
    CREUSR_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    CREDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    UPDUSR_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    UPDDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    CREDATTIM_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    UPDDATTIM_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    AUUID_0: Mapped[bytes] = mapped_column(BINARY(16))
    DAYMON_0: Mapped[int] = mapped_column(SmallInteger)
    DAYMON_1: Mapped[int] = mapped_column(SmallInteger)
    DAYMON_2: Mapped[int] = mapped_column(SmallInteger)
    DAYMON_3: Mapped[int] = mapped_column(SmallInteger)
    DAYMON_4: Mapped[int] = mapped_column(SmallInteger)
    DAYMON_5: Mapped[int] = mapped_column(SmallInteger)
    UVYCOD2_0: Mapped[str] = mapped_column(Unicode(5, 'Latin1_General_BIN2'))
    CSHVATRGM_0: Mapped[int] = mapped_column(TINYINT)
    CSHVATRGM_1: Mapped[int] = mapped_column(TINYINT)
    CSHVATRGM_2: Mapped[int] = mapped_column(TINYINT)
    CSHVATRGM_3: Mapped[int] = mapped_column(TINYINT)
    CSHVATRGM_4: Mapped[int] = mapped_column(TINYINT)
    CSHVATRGM_5: Mapped[int] = mapped_column(TINYINT)
    CSHVATRGM_6: Mapped[int] = mapped_column(TINYINT)
    CSHVATRGM_7: Mapped[int] = mapped_column(TINYINT)
    CSHVATRGM_8: Mapped[int] = mapped_column(TINYINT)
    VATSTRDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATSTRDAT_1: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATSTRDAT_2: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATSTRDAT_3: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATSTRDAT_4: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATSTRDAT_5: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATSTRDAT_6: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATSTRDAT_7: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATSTRDAT_8: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATENDDAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATENDDAT_1: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATENDDAT_2: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATENDDAT_3: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATENDDAT_4: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATENDDAT_5: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATENDDAT_6: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATENDDAT_7: Mapped[datetime.datetime] = mapped_column(DateTime)
    VATENDDAT_8: Mapped[datetime.datetime] = mapped_column(DateTime)
    BELVATSUB_0: Mapped[int] = mapped_column(SmallInteger)
    INVCND_0: Mapped[str] = mapped_column(Unicode(20, 'Latin1_General_BIN2'))
    ELECTINV_0: Mapped[int] = mapped_column(TINYINT)
    CNTEFAT_0: Mapped[str] = mapped_column(Unicode(15, 'Latin1_General_BIN2'))
    STRDATEFAT_0: Mapped[datetime.datetime] = mapped_column(DateTime)
    AEIFLG_0: Mapped[int] = mapped_column(SmallInteger)
    ZEDITOR_0: Mapped[int] = mapped_column(TINYINT)
    ZAGENTE_0: Mapped[int] = mapped_column(TINYINT)
    ZINTVSP_0: Mapped[int] = mapped_column(TINYINT)
    ZDISCRGVAL_0: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 3))
    ZEXPFLG_0: Mapped[int] = mapped_column(TINYINT)
    ZCRYNAM_0: Mapped[str] = mapped_column(Unicode(40, 'Latin1_General_BIN2'))
    ROWID: Mapped[decimal.Decimal] = mapped_column(
        Numeric(38, 0),
        Identity(start=decimal.Decimal('1'), increment=decimal.Decimal('1')),
        primary_key=True,
    )
